### ISSUE TITLE
i think this describes u a lot 😄 ur welcome :)

### ISSUE THREAD

**Issue by UnrealFar** [joskeph/joskeph#1]
[Removed to to violation in Repo guidelines]

**Comment by UnrealFar** [comment]
i think pics like theses are important to make the users aware of how awesome their devs are :)

**Comment by joskeph** [comment]
please do not leave strangers' pictures in this repo, this will not be accepted

**Comment by UnrealFar** [comment]
thats literally ur pic tho

**Comment by UnrealFar** [comment]
![image](https://github.com/joskeph/joskeph/assets/73272708/37c6ab9b-3c4a-4252-b18e-1c616a80bdba)
